# Generated by Django 5.2.4 on 2025-07-30 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin when creating order for user'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who created this order on behalf of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_free_meal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('payment_submitted', 'Payment Submitted'), ('low_stock', 'Low Stock Alert'), ('admin_order_created', 'Admin Created Order')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Submitted'), ('confirmed', 'Payment Confirmed'), ('preparing', 'Being Prepared'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('free', 'Free Meal (Institution Sponsored)')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.CreateModel(
            name='FreeMealDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(help_text='Reason for free meals (e.g., Company sponsored lunch)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_free_meal_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Free Meal Day',
                'verbose_name_plural': 'Free Meal Days',
                'ordering': ['-date'],
            },
        ),
    ]
